// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtkiqZ9kvxe-6SpIr-sJcGkzPVlstUjE',
    appId: '1:964272040303:web:39398a880de6e4fb8da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    authDomain: 'jarking-firebase.firebaseapp.com',
    storageBucket: 'jarking-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrGcHq6qFRefp81_FR4gD_u1ueruGw8JY',
    appId: '1:964272040303:android:3ab79cb6490f10d68da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    storageBucket: 'jarking-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxp8ZHFWiPNBiIOqEPKZgluMyYc1Ridk',
    appId: '1:964272040303:ios:fea2c044e2d3a3708da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    storageBucket: 'jarking-firebase.appspot.com',
    iosBundleId: 'com.example.finalProjectForFlutterByJarling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxp8ZHFWiPNBiIOqEPKZgluMyYc1Ridk',
    appId: '1:964272040303:ios:761b8b320984442f8da09a',
    messagingSenderId: '964272040303',
    projectId: 'jarking-firebase',
    storageBucket: 'jarking-firebase.appspot.com',
    iosBundleId: 'com.example.finalProjectForFlutterByJarling.RunnerTests',
  );
}
